version: "3.8"
services:
  api:
    image: 
    build: ./
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DB_URL: mongodb://db/amigos
  db:
    image: postgres
    environment:
      PGPASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES: amigos
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
