apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiltros
      tier: api
  template:
    metadata:
      labels:
        app: quiltros
        tier: api
    spec:
      containers:
        - name: api-container
          image: quiltros_api
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: quiltros
    tier: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
